# default:
#     trainer: ppo
#     batch_size: 1024
#     beta: 5.0e-3
#     buffer_size: 10240
#     epsilon: 0.2
#     hidden_units: 128
#     lambd: 0.95
#     learning_rate: 3.0e-4
#     learning_rate_schedule: linear
#     max_steps: 10.0e5
#     memory_size: 128
#     normalize: false
#     num_epoch: 3
#     num_layers: 2
#     time_horizon: 64
#     sequence_length: 64
#     summary_freq: 10000
#     use_recurrent: false
#     vis_encode_type: simple
#     reward_signals:
#         extrinsic:
#             strength: 1.0
#             gamma: 0.99

# Platform:
#     normalize: true
#     batch_size: 64
#     buffer_size: 12000
#     summary_freq: 12000
#     time_horizon: 1000
#     lambd: 0.99
#     beta: 0.001
# behaviors:
#     Platform:
#         trainer: ppo
#         batch_size: 64
#         beta: 0.001
#         buffer_size: 12000
#         epsilon: 0.2
#         hidden_units: 128
#         lambd: 0.99
#         learning_rate: 3.0e-4
#         learning_rate_schedule: linear
#         max_steps: 10.0e5
#         memory_size: 128
#         normalize: true
#         num_epoch: 3
#         num_layers: 2
#         time_horizon: 1000
#         sequence_length: 64
#         summary_freq: 12000
#         use_recurrent: false
#         vis_encode_type: simple
#         reward_signals:
#             extrinsic:
#                 strength: 1.0
#                 gamma: 0.99

behaviors:
  Platform:
    trainer_type: ppo
    hyperparameters:
      batch_size: 64
      buffer_size: 12000
      learning_rate: 0.0003
      beta: 0.001
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 500000
    time_horizon: 1000
    summary_freq: 12000
    threaded: true

# 3DBall:
#     normalize: true
#     batch_size: 64
#     buffer_size: 12000
#     summary_freq: 12000
#     time_horizon: 1000
#     lambd: 0.99
#     beta: 0.001

# 3DBallHard:
#     normalize: true
#     batch_size: 1200
#     buffer_size: 12000
#     summary_freq: 12000
#     time_horizon: 1000
#     max_steps: 5.0e6
#     beta: 0.001
#     reward_signals:
#         extrinsic:
#             strength: 1.0
#             gamma: 0.995

